# Ejemplos

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Camiseta Negra", 
    "price": 19.99, 
    "stock": 50, 
    "description": "Camiseta de algodón 100%, color negro.", 
    "category": "Ropa", 
    "image": "https://example.com/camiseta.jpg"
}

### 

POST http://localhost:3000/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Pantalones Azules", 
    "price": 29.99, 
    "stock": 30, 
    "description": "Pantalones de mezclilla, color azul.", 
    "category": "Ropa", 
    "image": "https://example.com/pantalones.jpg"
}

### 

GET http://localhost:3000/api/products HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/products/67af2f2e198947c36965623d HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/products/655a9b3e8b8747bc6a13a543 HTTP/1.1
content-type: application/json

{ 
    "name": "Camiseta Blanca", 
    "price": 24.99, 
    "stock": 40, 
    "description": "Camiseta de algodón 100%, color blanco.", 
    "category": "Ropa", 
    "image": "https://example.com/camiseta-blanca.jpg"
}

###

DELETE http://localhost:3000/api/products/6544f16661269657e5324e80 HTTP/1.1
content-type: application/json

###

DELETE https://nxapi-mongodb-3zee.vercel.app/api/products/67af298512d43ca75a090870 HTTP/1.1
content-type: application/json

### 

POST https://nxapi-mongodb-3zee.vercel.app/api/products HTTP/1.1
content-type: application/json

{ 
    "name": "Chaqueta de Cuero", 
    "price": 99.99, 
    "stock": 15, 
    "description": "Chaqueta de cuero genuino, color negro.", 
    "category": "Ropa", 
    "image": "https://example.com/chaqueta.jpg"
}

### 

DELETE https://nxapi-mongodb-3zee.vercel.app/api/products/6542da35c20d9ad95c739702 HTTP/1.1
content-type: application/json